import { useState } from 'react';
import { tokens } from '@/design/tokens';
import { downloadExport } from '../api/downloadExport';

/** The shared dictionary can always be re-seeded; a user's collected words + FSRS history can't be
 * regenerated by anyone. This gives them a real copy. */
export function ExportRow() {
  const [pending, setPending] = useState<'csv' | 'json' | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function handleExport(format: 'csv' | 'json') {
    setPending(format);
    setError(null);
    try {
      await downloadExport(format);
    } catch {
      setError('Export failed. Try again.');
    } finally {
      setPending(null);
    }
  }

  return (
    <div className="flex items-center justify-between gap-3">
      <div>
        <p className="font-bold" style={{ color: tokens.color.ink }}>
          Export my words
        </p>
        <p className="text-sm text-muted">Download your word bank and review history.</p>
        {error && <p className="text-xs font-semibold text-coral">{error}</p>}
      </div>
      <div className="flex gap-3">
        <button type="button" onClick={() => handleExport('csv')} disabled={pending !== null} className="text-sm font-bold text-teal disabled:opacity-40">
          {pending === 'csv' ? 'Exporting…' : 'CSV'}
        </button>
        <button type="button" onClick={() => handleExport('json')} disabled={pending !== null} className="text-sm font-bold text-teal disabled:opacity-40">
          {pending === 'json' ? 'Exporting…' : 'JSON'}
        </button>
      </div>
    </div>
  );
}
