export { PrismaClient, Prisma } from '../generated/prisma';
export type {
  User,
  Session,
  Account,
  Verification,
  Lexeme,
  Sense,
  WordForm,
  Example,
  ExampleWord,
  UserWord,
  Attempt,
  DrillSession,
  Task,
  Story,
  AiQuota,
  PartOfSpeech,
  Gender,
  Provenance,
  WordLevel,
  TaskType,
  AttemptResult,
  FsrsRating,
  DrillSessionStatus,
  TaskStatus,
  StoryStatus,
  AiSource,
  ExampleSource,
} from '../generated/prisma';
